### model
model_name_or_path: ./Llama-3.2-3B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: LogLM_train
template: alpaca
cutoff_len: 2048
max_samples: 1000
overwrite_cache: true
#preprocessing_num_workers: 1
preprocessing_num_workers: 16
#deepspeed: examples/deepspeed/ds_z2_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### output
output_dir: saves/Llama-3.2-3B-Instruct/full/sft
logging_steps: 10
save_steps: 10
plot_loss: true
overwrite_output_dir: true
save_total_limit: 3



### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 8
learning_rate: 2.0e-5
num_train_epochs: 6
lr_scheduler_type: cosine
warmup_ratio: 0.03
ddp_timeout: 180000000
save_strategy: epoch
weight_decay: 0.

### eval
#val_size: 0.1
#per_device_eval_batch_size: 1
#eval_strategy: steps
#eval_steps: 500


