### model
model_name_or_path: ./Meta-Llama-3-8B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full

### dataset
dataset: LogLM_train
template: alpaca
cutoff_len: 1024
max_samples: 128
batch_size: 128
overwrite_cache: true
preprocessing_num_workers: 1
deepspeed: examples/deepspeed/ds_z2_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### output
output_dir: saves/llama3-8b/full/sft
logging_steps: 10
save_steps: 50
plot_loss: true
overwrite_output_dir: true
save_total_limit: 3

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 1
learning_rate: 2e-5
num_train_epochs: 6
lr_scheduler_type: cosine
warmup_ratio: 0.03
ddp_timeout: 180000000
save_strategy: epoch
weight_decay: 0.

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500